####################################################################
##  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
##  SPDX-License-Identifier: MIT-0
####################################################################
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iam-cred-report-core"
s3_prefix = "iam-cred-report-core"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "pS3BucketStatus=\"New\" pKMSKeyStatus=\"New\" pKMSKeyArn=\"None\" pIAMCredentialGenRoleName=\"iam-credential-report-generation-role\" pOrganizationRootId=\"r-xxxx\" pOrganizationId=\"o-xxxxxxxxxx\" pLogsRetentionInDays=\"90\" pEventBridgeTriggerHour=\"08\" pTagKey1=\"tag-key\" pTagValue1=\"tag-value\""
image_repositories = []
